import type { WeaponDefinition, WeaponViewModelGltf } from "./weaponTypes";

const vm = (
  url: string,
  scale: number,
  position: [number, number, number],
  eulerDegrees: [number, number, number]
): WeaponViewModelGltf => ({ url, scale, position, eulerDegrees });

/** Shared first-person offsets (Blockbench gun models; tune per weapon if needed). */
const gunPos: [number, number, number] = [0.32, -0.26, -0.48];
const gunEu: [number, number, number] = [-3, 12, 0];
const smgScale = 0.32;
const rifleScale = 0.29;
const pistolScale = 0.34;
const heavyScale = 0.28;

const meleePos: [number, number, number] = [0.38, -0.22, -0.42];
const meleeEu: [number, number, number] = [-12, 78, 0];
const meleeScale = 0.38;

function meleeDef(
  id: string,
  name: string,
  shortName: string,
  file: string,
  damage: number,
  fireInt: number
): WeaponDefinition {
  return {
    id,
    name,
    shortName,
    caliber: "melee",
    shotProfile: "single",
    damage,
    headshotMultiplier: 1.35,
    fireIntervalSeconds: fireInt,
    range: 3.8,
    hitRadius: 0.85,
    spreadDegrees: 4,
    pelletsPerShot: 1,
    recoilKick: 0.02,
    magazineSize: 999,
    reserveAmmo: 0,
    reloadSeconds: 0,
    buyCost: 400,
    refillCost: 0,
    viewModelTint: [0.35, 0.3, 0.25],
    viewModelLength: 0.55,
    viewModelGltf: vm(`/models/weapons/hytopia-tools/${file}`, meleeScale, meleePos, meleeEu),
    audio: { shot: "shot" }
  };
}

/** Hytopia gun pack (paths under `public/models/weapons/hytopia-guns/`). */
export const HYTOPIA_GUN_DEFINITIONS = {
  ak47Fun: {
    id: "ak47Fun",
    name: "AK-47 (Fun)",
    shortName: "AK FUN",
    caliber: "7.62",
    shotProfile: "single",
    damage: 38,
    headshotMultiplier: 2.2,
    fireIntervalSeconds: 0.1,
    range: 90,
    hitRadius: 0.45,
    spreadDegrees: 1.4,
    pelletsPerShot: 1,
    recoilKick: 0.04,
    magazineSize: 30,
    reserveAmmo: 180,
    reloadSeconds: 2.35,
    buyCost: 2600,
    refillCost: 1150,
    viewModelTint: [0.4, 0.2, 0.35],
    viewModelLength: 0.8,
    viewModelGltf: vm("/models/weapons/hytopia-guns/ak47-fun.gltf", rifleScale, gunPos, gunEu),
    audio: { shot: "rifleShot" }
  },
  asval: {
    id: "asval",
    name: "AS VAL",
    shortName: "AS VAL",
    caliber: "9×39",
    shotProfile: "single",
    damage: 36,
    headshotMultiplier: 2.1,
    fireIntervalSeconds: 0.085,
    range: 78,
    hitRadius: 0.45,
    spreadDegrees: 1,
    pelletsPerShot: 1,
    recoilKick: 0.035,
    magazineSize: 20,
    reserveAmmo: 160,
    reloadSeconds: 2.2,
    buyCost: 2800,
    refillCost: 1200,
    viewModelTint: [0.22, 0.24, 0.2],
    viewModelLength: 0.75,
    viewModelGltf: vm("/models/weapons/hytopia-guns/asval.gltf", rifleScale, gunPos, gunEu),
    audio: { shot: "rifleShot" }
  },
  asvalFun: {
    id: "asvalFun",
    name: "AS VAL (Fun)",
    shortName: "VAL FUN",
    caliber: "9×39",
    shotProfile: "single",
    damage: 34,
    headshotMultiplier: 2,
    fireIntervalSeconds: 0.085,
    range: 76,
    hitRadius: 0.45,
    spreadDegrees: 1.2,
    pelletsPerShot: 1,
    recoilKick: 0.036,
    magazineSize: 20,
    reserveAmmo: 160,
    reloadSeconds: 2.2,
    buyCost: 2700,
    refillCost: 1180,
    viewModelTint: [0.35, 0.15, 0.4],
    viewModelLength: 0.75,
    viewModelGltf: vm("/models/weapons/hytopia-guns/asval-fun.gltf", rifleScale, gunPos, gunEu),
    audio: { shot: "rifleShot" }
  },
  awp: {
    id: "awp",
    name: "AWP",
    shortName: "AWP",
    caliber: ".338",
    shotProfile: "single",
    damage: 115,
    headshotMultiplier: 1.65,
    fireIntervalSeconds: 1.35,
    range: 140,
    hitRadius: 0.38,
    spreadDegrees: 0.25,
    pelletsPerShot: 1,
    recoilKick: 0.085,
    magazineSize: 10,
    reserveAmmo: 40,
    reloadSeconds: 3.2,
    buyCost: 4200,
    refillCost: 2000,
    viewModelTint: [0.18, 0.22, 0.16],
    viewModelLength: 0.95,
    viewModelGltf: vm("/models/weapons/hytopia-guns/awp.gltf", heavyScale, gunPos, [-2, 10, 0]),
    audio: { shot: "rifleShot" }
  },
  awpFun: {
    id: "awpFun",
    name: "AWP (Fun)",
    shortName: "AWP FUN",
    caliber: ".338",
    shotProfile: "single",
    damage: 105,
    headshotMultiplier: 1.6,
    fireIntervalSeconds: 1.25,
    range: 135,
    hitRadius: 0.38,
    spreadDegrees: 0.35,
    pelletsPerShot: 1,
    recoilKick: 0.08,
    magazineSize: 10,
    reserveAmmo: 40,
    reloadSeconds: 3.1,
    buyCost: 4100,
    refillCost: 1950,
    viewModelTint: [0.4, 0.18, 0.28],
    viewModelLength: 0.95,
    viewModelGltf: vm("/models/weapons/hytopia-guns/awp-fun.gltf", heavyScale, gunPos, [-2, 10, 0]),
    audio: { shot: "rifleShot" }
  },
  desertEagle: {
    id: "desertEagle",
    name: "Desert Eagle",
    shortName: "DEAGLE",
    caliber: ".50 AE",
    shotProfile: "single",
    damage: 62,
    headshotMultiplier: 2.4,
    fireIntervalSeconds: 0.32,
    range: 62,
    hitRadius: 0.48,
    spreadDegrees: 1.8,
    pelletsPerShot: 1,
    recoilKick: 0.045,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadSeconds: 2,
    buyCost: 1600,
    refillCost: 700,
    viewModelTint: [0.25, 0.22, 0.2],
    viewModelLength: 0.52,
    viewModelGltf: vm("/models/weapons/hytopia-guns/desert-eagle.gltf", 0.33, [0.36, -0.24, -0.5], [-5, 7, 0]),
    audio: { shot: "magnumShot" }
  },
  desertEagleGold: {
    id: "desertEagleGold",
    name: "Desert Eagle (Gold)",
    shortName: "DEAGLE Au",
    caliber: ".50 AE",
    shotProfile: "single",
    damage: 64,
    headshotMultiplier: 2.45,
    fireIntervalSeconds: 0.32,
    range: 62,
    hitRadius: 0.48,
    spreadDegrees: 1.7,
    pelletsPerShot: 1,
    recoilKick: 0.045,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadSeconds: 2,
    buyCost: 3200,
    refillCost: 900,
    viewModelTint: [0.55, 0.45, 0.12],
    viewModelLength: 0.52,
    viewModelGltf: vm("/models/weapons/hytopia-guns/desert-eagle-gold.gltf", 0.33, [0.36, -0.24, -0.5], [-5, 7, 0]),
    audio: { shot: "magnumShot" }
  },
  glock19Blue: {
    id: "glock19Blue",
    name: "Glock 19 (Blue)",
    shortName: "G19 BL",
    caliber: "9mm",
    shotProfile: "single",
    damage: 30,
    headshotMultiplier: 2.2,
    fireIntervalSeconds: 0.18,
    range: 58,
    hitRadius: 0.5,
    spreadDegrees: 1.5,
    pelletsPerShot: 1,
    recoilKick: 0.012,
    magazineSize: 12,
    reserveAmmo: 96,
    reloadSeconds: 1.5,
    buyCost: 500,
    refillCost: 250,
    viewModelTint: [0.15, 0.28, 0.55],
    viewModelLength: 0.5,
    viewModelGltf: vm("/models/weapons/hytopia-guns/glock-19-blue.gltf", pistolScale, [0.38, -0.22, -0.52], [-4, 8, 0]),
    audio: { shot: "shot" }
  },
  glock19Green: {
    id: "glock19Green",
    name: "Glock 19 (Green)",
    shortName: "G19 GR",
    caliber: "9mm",
    shotProfile: "single",
    damage: 30,
    headshotMultiplier: 2.2,
    fireIntervalSeconds: 0.18,
    range: 58,
    hitRadius: 0.5,
    spreadDegrees: 1.5,
    pelletsPerShot: 1,
    recoilKick: 0.012,
    magazineSize: 12,
    reserveAmmo: 96,
    reloadSeconds: 1.5,
    buyCost: 500,
    refillCost: 250,
    viewModelTint: [0.18, 0.45, 0.22],
    viewModelLength: 0.5,
    viewModelGltf: vm("/models/weapons/hytopia-guns/glock-19-green.gltf", pistolScale, [0.38, -0.22, -0.52], [-4, 8, 0]),
    audio: { shot: "shot" }
  },
  glock19Pink: {
    id: "glock19Pink",
    name: "Glock 19 (Pink)",
    shortName: "G19 PK",
    caliber: "9mm",
    shotProfile: "single",
    damage: 30,
    headshotMultiplier: 2.2,
    fireIntervalSeconds: 0.18,
    range: 58,
    hitRadius: 0.5,
    spreadDegrees: 1.5,
    pelletsPerShot: 1,
    recoilKick: 0.012,
    magazineSize: 12,
    reserveAmmo: 96,
    reloadSeconds: 1.5,
    buyCost: 500,
    refillCost: 250,
    viewModelTint: [0.55, 0.22, 0.4],
    viewModelLength: 0.5,
    viewModelGltf: vm("/models/weapons/hytopia-guns/glock-19-pink.gltf", pistolScale, [0.38, -0.22, -0.52], [-4, 8, 0]),
    audio: { shot: "shot" }
  },
  m4a4: {
    id: "m4a4",
    name: "M4A4",
    shortName: "M4A4",
    caliber: "5.56",
    shotProfile: "single",
    damage: 37,
    headshotMultiplier: 2.25,
    fireIntervalSeconds: 0.088,
    range: 90,
    hitRadius: 0.44,
    spreadDegrees: 0.9,
    pelletsPerShot: 1,
    recoilKick: 0.033,
    magazineSize: 30,
    reserveAmmo: 210,
    reloadSeconds: 2.15,
    buyCost: 2200,
    refillCost: 1000,
    viewModelTint: [0.22, 0.2, 0.18],
    viewModelLength: 0.82,
    viewModelGltf: vm("/models/weapons/hytopia-guns/m4a4.gltf", rifleScale, gunPos, gunEu),
    audio: { shot: "rifleShot" }
  },
  m4a4Fun: {
    id: "m4a4Fun",
    name: "M4A4 (Fun)",
    shortName: "M4 FUN",
    caliber: "5.56",
    shotProfile: "single",
    damage: 35,
    headshotMultiplier: 2.15,
    fireIntervalSeconds: 0.088,
    range: 88,
    hitRadius: 0.44,
    spreadDegrees: 1.05,
    pelletsPerShot: 1,
    recoilKick: 0.034,
    magazineSize: 30,
    reserveAmmo: 210,
    reloadSeconds: 2.15,
    buyCost: 2300,
    refillCost: 1020,
    viewModelTint: [0.38, 0.2, 0.3],
    viewModelLength: 0.82,
    viewModelGltf: vm("/models/weapons/hytopia-guns/m4a4-fun.gltf", rifleScale, gunPos, gunEu),
    audio: { shot: "rifleShot" }
  },
  mp7: {
    id: "mp7",
    name: "MP7",
    shortName: "MP7",
    caliber: "9mm",
    shotProfile: "burst",
    damage: 22,
    headshotMultiplier: 1.9,
    fireIntervalSeconds: 0.06,
    range: 54,
    hitRadius: 0.5,
    spreadDegrees: 2.8,
    pelletsPerShot: 1,
    recoilKick: 0.022,
    magazineSize: 40,
    reserveAmmo: 200,
    reloadSeconds: 1.9,
    buyCost: 1900,
    refillCost: 850,
    viewModelTint: [0.2, 0.22, 0.24],
    viewModelLength: 0.58,
    viewModelGltf: vm("/models/weapons/hytopia-guns/mp7.gltf", smgScale, [0.34, -0.25, -0.46], [-4, 11, 0]),
    audio: { shot: "smgShot" }
  }
} satisfies Record<string, WeaponDefinition>;

const MELEE_FILES = [
  { id: "diamondAxe", name: "Diamond Axe", short: "Dm.Axe", file: "diamond-axe.gltf", d: 58 },
  { id: "diamondHoe", name: "Diamond Hoe", short: "Dm.Hoe", file: "diamond-hoe.gltf" },
  { id: "diamondShovel", name: "Diamond Shovel", short: "Dm.Shv", file: "diamond-shovel.gltf" },
  { id: "diamondPickaxe", name: "Diamond Pickaxe", short: "Dm.Pick", file: "diamond-pickaxe.gltf", d: 56 },
  { id: "emeraldAxe", name: "Emerald Axe", short: "Em.Axe", file: "emerald-axe.gltf", d: 56 },
  { id: "emeraldHoe", name: "Emerald Hoe", short: "Em.Hoe", file: "emerald-hoe.gltf" },
  { id: "emeraldShovel", name: "Emerald Shovel", short: "Em.Shv", file: "emerald-shovel.gltf" },
  { id: "emeraldPickaxe", name: "Emerald Pickaxe", short: "Em.Pick", file: "emerald-pickaxe.gltf", d: 54 },
  { id: "goldenAxe", name: "Golden Axe", short: "Au.Axe", file: "golden-axe.gltf", d: 52 },
  { id: "goldenHoe", name: "Golden Hoe", short: "Au.Hoe", file: "golden-hoe.gltf" },
  { id: "goldenShovel", name: "Golden Shovel", short: "Au.Shv", file: "golden-shovel.gltf" },
  { id: "goldenPickaxe", name: "Golden Pickaxe", short: "Au.Pick", file: "golden-pickaxe.gltf", d: 50 },
  { id: "ironAxe", name: "Iron Axe", short: "Fe.Axe", file: "iron-axe.gltf", d: 50 },
  { id: "ironHoe", name: "Iron Hoe", short: "Fe.Hoe", file: "iron-hoe.gltf" },
  { id: "ironShovel", name: "Iron Shovel", short: "Fe.Shv", file: "iron-shovel.gltf" },
  { id: "ironPickaxe", name: "Iron Pickaxe", short: "Fe.Pick", file: "iron-pickaxe.gltf", d: 48 },
  { id: "rubyAxe", name: "Ruby Axe", short: "Rb.Axe", file: "ruby-axe.gltf", d: 58 },
  { id: "rubyHoe", name: "Ruby Hoe", short: "Rb.Hoe", file: "ruby-hoe.gltf" },
  { id: "rubyShovel", name: "Ruby Shovel", short: "Rb.Shv", file: "ruby-shovel.gltf" },
  { id: "rubyPickaxe", name: "Ruby Pickaxe", short: "Rb.Pick", file: "ruby-pickaxe.gltf", d: 56 },
  { id: "sapphireAxe", name: "Sapphire Axe", short: "Sa.Axe", file: "sapphire-axe.gltf", d: 56 },
  { id: "sapphireHoe", name: "Sapphire Hoe", short: "Sa.Hoe", file: "sapphire-hoe.gltf" },
  { id: "sapphireShovel", name: "Sapphire Shovel", short: "Sa.Shv", file: "sapphire-shovel.gltf" },
  { id: "sapphirePickaxe", name: "Sapphire Pickaxe", short: "Sa.Pick", file: "sapphire-pickaxe.gltf", d: 54 },
  { id: "stoneAxe", name: "Stone Axe", short: "St.Axe", file: "stone-axe.gltf", d: 44 },
  { id: "stoneHoe", name: "Stone Hoe", short: "St.Hoe", file: "stone-hoe.gltf" },
  { id: "stoneShovel", name: "Stone Shovel", short: "St.Shv", file: "stone-shovel.gltf" },
  { id: "stonePickaxe", name: "Stone Pickaxe", short: "St.Pick", file: "stone-pickaxe.gltf", d: 42 },
  { id: "swordDiamond", name: "Diamond Sword", short: "Dm.Sw", file: "sword-diamond.gltf", d: 62, t: 0.48 },
  { id: "swordEmerald", name: "Emerald Sword", short: "Em.Sw", file: "sword-emerald.gltf", d: 60, t: 0.48 },
  { id: "swordGolden", name: "Golden Sword", short: "Au.Sw", file: "sword-golden.gltf", d: 54, t: 0.45 },
  { id: "swordIron", name: "Iron Sword", short: "Fe.Sw", file: "sword-iron.gltf", d: 52, t: 0.45 },
  { id: "swordRuby", name: "Ruby Sword", short: "Rb.Sw", file: "sword-ruby.gltf", d: 62, t: 0.48 },
  { id: "swordSapphire", name: "Sapphire Sword", short: "Sa.Sw", file: "sword-sapphire.gltf", d: 60, t: 0.48 },
  { id: "swordStone", name: "Stone Sword", short: "St.Sw", file: "sword-stone.gltf", d: 46, t: 0.5 },
  { id: "swordWooden", name: "Wooden Sword", short: "Wd.Sw", file: "sword-wooden.gltf", d: 42, t: 0.52 },
  { id: "woodenAxe", name: "Wooden Axe", short: "Wd.Axe", file: "wooden-axe.gltf", d: 40 },
  { id: "woodenHoe", name: "Wooden Hoe", short: "Wd.Hoe", file: "wooden-hoe.gltf" },
  { id: "woodenShovel", name: "Wooden Shovel", short: "Wd.Shv", file: "wooden-shovel.gltf" },
  { id: "woodenPickaxe", name: "Wooden Pickaxe", short: "Wd.Pick", file: "wooden-pickaxe.gltf", d: 38 }
] as const;

export type HytopiaMeleeWeaponId = (typeof MELEE_FILES)[number]["id"];

export const HYTOPIA_MELEE_DEFINITIONS = MELEE_FILES.reduce(
  (acc, m) => {
    const damage = "d" in m ? m.d : 48;
    const fireInt = "t" in m ? m.t : 0.55;
    acc[m.id] = meleeDef(m.id, m.name, m.short, m.file, damage, fireInt);
    return acc;
  },
  {} as Record<HytopiaMeleeWeaponId, WeaponDefinition>
);
